name: Django CI
on:
  pull_request:
    branches: [main]
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          DB_NAME: neondb
          DB_USER: neondb_owner
          DB_PASSWORD: npg_Y8v0SiBjyOLW
          DB_HOST: p-small-band-a4mcmsuz-pooler.us-east-1.aws.neon.tech
          DB_PORT: 5432
          DB_SSLMODE: enable
        run: |
          python -m pytest